<?php

declare(strict_types=1);

namespace Mirakl\MMP\Common\Domain\SellerBillingCycle;

use Mirakl\Core\Domain\MiraklObject;

/**
 * @method float getTotalCommissionsExclTax()
 * @method $this setTotalCommissionsExclTax(float $totalCommissionsExclTax)
 * @method float getTotalCommissionsInclTax()
 * @method $this setTotalCommissionsInclTax(float $totalCommissionsInclTax)
 * @method float getTotalFeeExclTax()
 * @method $this setTotalFeeExclTax(float $totalFeeExclTax)
 * @method float getTotalFeeInclTax()
 * @method $this setTotalFeeInclTax(float $totalFeeInclTax)
 * @method float getTotalFeeOperatorRemittedExclTax()
 * @method $this setTotalFeeOperatorRemittedExclTax(float $totalFeeOperatorRemittedExclTax)
 * @method float getTotalFeeOperatorRemittedInclTax()
 * @method $this setTotalFeeOperatorRemittedInclTax(float $totalFeeOperatorRemittedInclTax)
 * @method float getTotalNonPayableOrdersExclTax()
 * @method $this setTotalNonPayableOrdersExclTax(float $totalNonPayableOrdersExclTax)
 * @method float getTotalNonPayableOrdersInclTax()
 * @method $this setTotalNonPayableOrdersInclTax(float $totalNonPayableOrdersInclTax)
 * @method float getTotalOperatorPaidShippingChargesExclTax()
 * @method $this setTotalOperatorPaidShippingChargesExclTax(float $totalOperatorPaidShippingChargesExclTax)
 * @method float getTotalOperatorPaidShippingChargesInclTax()
 * @method $this setTotalOperatorPaidShippingChargesInclTax(float $totalOperatorPaidShippingChargesInclTax)
 * @method float getTotalOperatorRemittedTaxes()
 * @method $this setTotalOperatorRemittedTaxes(float $totalOperatorRemittedTaxes)
 * @method float getTotalOtherCreditsExclTax()
 * @method $this setTotalOtherCreditsExclTax(float $totalOtherCreditsExclTax)
 * @method float getTotalOtherCreditsInclTax()
 * @method $this setTotalOtherCreditsInclTax(float $totalOtherCreditsInclTax)
 * @method float getTotalOtherInvoicesExclTax()
 * @method $this setTotalOtherInvoicesExclTax(float $totalOtherInvoicesExclTax)
 * @method float getTotalOtherInvoicesInclTax()
 * @method $this setTotalOtherInvoicesInclTax(float $totalOtherInvoicesInclTax)
 * @method float getTotalPayableOrdersExclTax()
 * @method $this setTotalPayableOrdersExclTax(float $totalPayableOrdersExclTax)
 * @method float getTotalPayableOrdersInclTax()
 * @method $this setTotalPayableOrdersInclTax(float $totalPayableOrdersInclTax)
 * @method float getTotalPurchaseTaxes()
 * @method $this setTotalPurchaseTaxes(float $totalPurchaseTaxes)
 * @method float getTotalRefundCommissionsExclTax()
 * @method $this setTotalRefundCommissionsExclTax(float $totalRefundCommissionsExclTax)
 * @method float getTotalRefundCommissionsInclTax()
 * @method $this setTotalRefundCommissionsInclTax(float $totalRefundCommissionsInclTax)
 * @method float getTotalRefundFeeExclTax()
 * @method $this setTotalRefundFeeExclTax(float $totalRefundFeeExclTax)
 * @method float getTotalRefundFeeInclTax()
 * @method $this setTotalRefundFeeInclTax(float $totalRefundFeeInclTax)
 * @method float getTotalRefundFeeOperatorRemittedExclTax()
 * @method $this setTotalRefundFeeOperatorRemittedExclTax(float $totalRefundFeeOperatorRemittedExclTax)
 * @method float getTotalRefundFeeOperatorRemittedInclTax()
 * @method $this setTotalRefundFeeOperatorRemittedInclTax(float $totalRefundFeeOperatorRemittedInclTax)
 * @method float getTotalRefundNonPayableOrdersExclTax()
 * @method $this setTotalRefundNonPayableOrdersExclTax(float $totalRefundNonPayableOrdersExclTax)
 * @method float getTotalRefundNonPayableOrdersInclTax()
 * @method $this setTotalRefundNonPayableOrdersInclTax(float $totalRefundNonPayableOrdersInclTax)
 * @method float getTotalRefundOperatorPaidShippingChargesExclTax()
 * @method $this setTotalRefundOperatorPaidShippingChargesExclTax(float $totalRefundOperatorPaidShippingChargesExclTax)
 * @method float getTotalRefundOperatorPaidShippingChargesInclTax()
 * @method $this setTotalRefundOperatorPaidShippingChargesInclTax(float $totalRefundOperatorPaidShippingChargesInclTax)
 * @method float getTotalRefundOperatorRemittedTaxes()
 * @method $this setTotalRefundOperatorRemittedTaxes(float $totalRefundOperatorRemittedTaxes)
 * @method float getTotalRefundOrdersExclTax()
 * @method $this setTotalRefundOrdersExclTax(float $totalRefundOrdersExclTax)
 * @method float getTotalRefundOrdersInclTax()
 * @method $this setTotalRefundOrdersInclTax(float $totalRefundOrdersInclTax)
 * @method float getTotalRefundPayableOrdersExclTax()
 * @method $this setTotalRefundPayableOrdersExclTax(float $totalRefundPayableOrdersExclTax)
 * @method float getTotalRefundPayableOrdersInclTax()
 * @method $this setTotalRefundPayableOrdersInclTax(float $totalRefundPayableOrdersInclTax)
 * @method float getTotalRefundPurchaseTaxes()
 * @method $this setTotalRefundPurchaseTaxes(float $totalRefundPurchaseTaxes)
 * @method float getTotalSellerFeesOnOrdersExclTax()
 * @method $this setTotalSellerFeesOnOrdersExclTax(float $totalSellerFeesOnOrdersExclTax)
 * @method float getTotalSellerFeesOnOrdersInclTax()
 * @method $this setTotalSellerFeesOnOrdersInclTax(float $totalSellerFeesOnOrdersInclTax)
 * @method float getTotalSellerPenaltyFeesExclTax()
 * @method $this setTotalSellerPenaltyFeesExclTax(float $totalSellerPenaltyFeesExclTax)
 * @method float getTotalSellerPenaltyFeesInclTax()
 * @method $this setTotalSellerPenaltyFeesInclTax(float $totalSellerPenaltyFeesInclTax)
 * @method float getTotalSubscriptionExclTax()
 * @method $this setTotalSubscriptionExclTax(float $totalSubscriptionExclTax)
 * @method float getTotalSubscriptionInclTax()
 * @method $this setTotalSubscriptionInclTax(float $totalSubscriptionInclTax)
 */
class Summary extends MiraklObject
{
}
